name: Docker Image CI CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  IMAGE_NAME: aws-container-photo-ui
  IMAGE_TAG: ${{ github.run_id }}

jobs:

  build_image:
    name: Build Container Image  

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src #photo-app-ui

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
